import 'dart:ui';

import 'growth_island_config_models.dart';

class GrowthIslandConfigs {
  GrowthIslandConfigs._();

  static const zones = <ZoneConfig>[
    ZoneConfig(
      id: 'CenterZone',
      name: 'Center',
      priority: 50,
      bounds: Rect.fromLTWH(0.34, 0.34, 0.32, 0.28),
      allowedBuildings: [
        'starter_stone',
        'growth_house',
        'growth_house_lv2',
        'memory_fountain',
        'growth_clocktower',
        'growth_academy',
      ],
      allowedDecorations: ['grass_patch', 'tiny_flower', 'center_lawn_ring'],
    ),
    ZoneConfig(
      id: 'EmotionZone',
      name: 'Emotion',
      priority: 30,
      bounds: Rect.fromLTWH(0.32, 0.56, 0.36, 0.24),
      allowedBuildings: ['emotion_windchime', 'habit_flowerbed', 'quiet_tent'],
      allowedDecorations: [
        'flower_group_a',
        'firefly_dot',
        'soft_cloud_shadow',
      ],
    ),
    ZoneConfig(
      id: 'MemoryZone',
      name: 'Memory',
      priority: 20,
      bounds: Rect.fromLTWH(0.10, 0.34, 0.28, 0.34),
      allowedBuildings: [
        'record_shed',
        'memory_mailbox',
        'memory_gallery',
      ],
      allowedDecorations: ['guardian_tree', 'small_stone', 'bush_low'],
    ),
    ZoneConfig(
      id: 'KnowledgeZone',
      name: 'Knowledge',
      priority: 20,
      bounds: Rect.fromLTWH(0.62, 0.34, 0.28, 0.34),
      allowedBuildings: [
        'lighthouse_base',
        'story_plaza',
        'library_seed',
      ],
      allowedDecorations: [
        'stream_a',
        'bridge_small',
        'roadside_tree',
        'flower_line',
        'book_flowerbed',
      ],
    ),
    ZoneConfig(
      id: 'FutureZone',
      name: 'Future',
      priority: 10,
      bounds: Rect.fromLTWH(0.30, 0.14, 0.40, 0.26),
      allowedBuildings: ['lighthouse', 'dream_observatory'],
      allowedDecorations: [
        'far_hill',
        'tall_tree',
        'large_canopy',
        'bird_group',
        'cloud_far',
      ],
    ),
    ZoneConfig(
      id: 'HarborZone',
      name: 'Harbor',
      priority: 40,
      bounds: Rect.fromLTWH(0.12, 0.62, 0.28, 0.24),
      allowedBuildings: ['harbor_pier', 'companion_plaza'],
      allowedDecorations: [
        'reed_edge',
        'shore_rock',
        'life_area_fence',
        'bench_small',
        'lamp_post',
        'long_bench',
        'low_fence',
      ],
    ),
  ];

  static const buildings = <BuildingConfig>[
    BuildingConfig(
      id: 'starter_stone',
      name: 'Starter Stone',
      type: 'stone',
      unlockLevel: 1,
      zone: 'CenterZone',
      position: Offset(0.50, 0.50),
      size: Offset(0.08, 0.07),
      sprite: 'buildings/starter_stone.png',
      animation: 'idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'record_shed',
      name: 'Record Shed',
      type: 'shed',
      unlockLevel: 3,
      zone: 'MemoryZone',
      position: Offset(0.30, 0.51),
      size: Offset(0.13, 0.11),
      sprite: 'buildings/record_shed.png',
      animation: 'idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'memory_mailbox',
      name: 'Memory Mailbox',
      type: 'mailbox',
      unlockLevel: 4,
      zone: 'MemoryZone',
      position: Offset(0.24, 0.58),
      size: Offset(0.08, 0.08),
      sprite: 'buildings/memory_mailbox.png',
      animation: 'idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'growth_house',
      name: 'Growth House',
      type: 'house',
      unlockLevel: 5,
      zone: 'CenterZone',
      position: Offset(0.50, 0.43),
      size: Offset(0.16, 0.14),
      sprite: 'buildings/growth_house.png',
      animation: 'warm_idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'growth_house_lv2',
      name: 'Growth House Lv2',
      type: 'house',
      unlockLevel: 10,
      zone: 'CenterZone',
      position: Offset(0.50, 0.43),
      size: Offset(0.18, 0.16),
      sprite: 'buildings/growth_house_lv2.png',
      animation: 'warm_idle',
      interactionType: 'inspect',
      upgradeLevel: 2,
    ),
    BuildingConfig(
      id: 'harbor_pier',
      name: 'Harbor Pier',
      type: 'pier',
      unlockLevel: 6,
      zone: 'HarborZone',
      position: Offset(0.22, 0.72),
      size: Offset(0.16, 0.10),
      sprite: 'buildings/harbor_pier.png',
      animation: 'water_idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'emotion_windchime',
      name: 'Emotion Windchime',
      type: 'windchime',
      unlockLevel: 7,
      zone: 'EmotionZone',
      position: Offset(0.42, 0.66),
      size: Offset(0.10, 0.12),
      sprite: 'buildings/emotion_windchime.png',
      animation: 'sway',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'habit_flowerbed',
      name: 'Habit Flowerbed',
      type: 'flowerbed',
      unlockLevel: 8,
      zone: 'EmotionZone',
      position: Offset(0.58, 0.66),
      size: Offset(0.14, 0.08),
      sprite: 'buildings/habit_flowerbed.png',
      animation: 'bloom',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'quiet_tent',
      name: 'Quiet Tent',
      type: 'tent',
      unlockLevel: 9,
      zone: 'EmotionZone',
      position: Offset(0.50, 0.70),
      size: Offset(0.13, 0.10),
      sprite: 'buildings/quiet_tent.png',
      animation: 'idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'lighthouse_base',
      name: 'Lighthouse Base',
      type: 'lighthouse_base',
      unlockLevel: 11,
      zone: 'KnowledgeZone',
      position: Offset(0.72, 0.48),
      size: Offset(0.12, 0.12),
      sprite: 'buildings/lighthouse_base.png',
      animation: 'idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'story_plaza',
      name: 'Story Plaza',
      type: 'plaza',
      unlockLevel: 12,
      zone: 'KnowledgeZone',
      position: Offset(0.66, 0.56),
      size: Offset(0.16, 0.10),
      sprite: 'buildings/story_plaza.png',
      animation: 'spark',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'memory_fountain',
      name: 'Memory Fountain',
      type: 'fountain',
      unlockLevel: 13,
      zone: 'CenterZone',
      position: Offset(0.50, 0.50),
      size: Offset(0.14, 0.12),
      sprite: 'buildings/memory_fountain.png',
      animation: 'water_idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'library_seed',
      name: 'Library Seed',
      type: 'library',
      unlockLevel: 14,
      zone: 'KnowledgeZone',
      position: Offset(0.78, 0.43),
      size: Offset(0.16, 0.13),
      sprite: 'buildings/library_seed.png',
      animation: 'page_float',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'growth_clocktower',
      name: 'Growth Clocktower',
      type: 'clocktower',
      unlockLevel: 15,
      zone: 'CenterZone',
      position: Offset(0.50, 0.36),
      size: Offset(0.13, 0.18),
      sprite: 'buildings/growth_clocktower.png',
      animation: 'clock_light',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'lighthouse',
      name: 'Lighthouse',
      type: 'lighthouse',
      unlockLevel: 16,
      zone: 'FutureZone',
      position: Offset(0.65, 0.27),
      size: Offset(0.12, 0.18),
      sprite: 'buildings/lighthouse.png',
      animation: 'beam',
      interactionType: 'inspect',
      upgradeLevel: 2,
    ),
    BuildingConfig(
      id: 'companion_plaza',
      name: 'Companion Plaza',
      type: 'plaza',
      unlockLevel: 17,
      zone: 'HarborZone',
      position: Offset(0.34, 0.70),
      size: Offset(0.16, 0.10),
      sprite: 'buildings/companion_plaza.png',
      animation: 'life_idle',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'memory_gallery',
      name: 'Memory Gallery',
      type: 'gallery',
      unlockLevel: 18,
      zone: 'MemoryZone',
      position: Offset(0.20, 0.44),
      size: Offset(0.17, 0.13),
      sprite: 'buildings/memory_gallery.png',
      animation: 'glow',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'dream_observatory',
      name: 'Dream Observatory',
      type: 'observatory',
      unlockLevel: 19,
      zone: 'FutureZone',
      position: Offset(0.42, 0.27),
      size: Offset(0.16, 0.14),
      sprite: 'buildings/dream_observatory.png',
      animation: 'glimmer',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
    BuildingConfig(
      id: 'growth_academy',
      name: 'Growth Academy',
      type: 'academy',
      unlockLevel: 20,
      zone: 'CenterZone',
      position: Offset(0.50, 0.38),
      size: Offset(0.24, 0.18),
      sprite: 'buildings/growth_academy.png',
      animation: 'complete_aura',
      interactionType: 'inspect',
      upgradeLevel: 1,
    ),
  ];

  static const decorations = <DecorationConfig>[
    DecorationConfig(
        id: 'grass_patch',
        type: 'grass',
        unlockLevel: 1,
        zone: 'CenterZone',
        density: 0.8,
        asset: 'decor/grass.png',
        animation: 'sway',
        randomSeed: 11),
    DecorationConfig(
        id: 'tiny_flower',
        type: 'flower',
        unlockLevel: 1,
        zone: 'CenterZone',
        density: 0.5,
        asset: 'decor/tiny_flower.png',
        animation: 'idle',
        randomSeed: 12),
    DecorationConfig(
        id: 'footprint_grass',
        type: 'grass',
        unlockLevel: 2,
        zone: 'CenterZone',
        density: 0.35,
        asset: 'decor/footprint_grass.png',
        animation: 'idle',
        randomSeed: 21),
    DecorationConfig(
        id: 'guardian_tree',
        type: 'tree',
        unlockLevel: 3,
        zone: 'MemoryZone',
        density: 0.25,
        asset: 'decor/guardian_tree.png',
        animation: 'sway',
        randomSeed: 31),
    DecorationConfig(
        id: 'small_stone',
        type: 'bush',
        unlockLevel: 4,
        zone: 'MemoryZone',
        density: 0.35,
        asset: 'decor/small_stone.png',
        animation: 'idle',
        randomSeed: 41),
    DecorationConfig(
        id: 'bush_low',
        type: 'bush',
        unlockLevel: 4,
        zone: 'MemoryZone',
        density: 0.4,
        asset: 'decor/bush_low.png',
        animation: 'sway',
        randomSeed: 42),
    DecorationConfig(
        id: 'center_lawn_ring',
        type: 'grass',
        unlockLevel: 5,
        zone: 'CenterZone',
        density: 0.45,
        asset: 'decor/lawn_ring.png',
        animation: 'idle',
        randomSeed: 51),
    DecorationConfig(
        id: 'reed_edge',
        type: 'grass',
        unlockLevel: 6,
        zone: 'HarborZone',
        density: 0.45,
        asset: 'decor/reed_edge.png',
        animation: 'sway',
        randomSeed: 61),
    DecorationConfig(
        id: 'shore_rock',
        type: 'bush',
        unlockLevel: 6,
        zone: 'HarborZone',
        density: 0.4,
        asset: 'decor/shore_rock.png',
        animation: 'idle',
        randomSeed: 62),
    DecorationConfig(
        id: 'tree_cluster_west',
        type: 'tree',
        unlockLevel: 7,
        zone: 'MemoryZone',
        density: 0.4,
        asset: 'decor/tree_cluster_west.png',
        animation: 'sway',
        randomSeed: 71),
    DecorationConfig(
        id: 'flower_group_a',
        type: 'flower',
        unlockLevel: 8,
        zone: 'EmotionZone',
        density: 0.55,
        asset: 'decor/flower_group_a.png',
        animation: 'bloom',
        randomSeed: 81),
    DecorationConfig(
        id: 'soft_cloud_shadow',
        type: 'grass',
        unlockLevel: 9,
        zone: 'EmotionZone',
        density: 0.35,
        asset: 'decor/cloud_shadow.png',
        animation: 'idle',
        randomSeed: 91),
    DecorationConfig(
        id: 'firefly_dot',
        type: 'flower',
        unlockLevel: 9,
        zone: 'EmotionZone',
        density: 0.3,
        asset: 'decor/firefly_dot.png',
        animation: 'glow',
        randomSeed: 92),
    DecorationConfig(
        id: 'life_area_fence',
        type: 'bush',
        unlockLevel: 10,
        zone: 'HarborZone',
        density: 0.25,
        asset: 'decor/life_area_fence.png',
        animation: 'idle',
        randomSeed: 101),
    DecorationConfig(
        id: 'bench_small',
        type: 'bush',
        unlockLevel: 10,
        zone: 'HarborZone',
        density: 0.2,
        asset: 'decor/bench_small.png',
        animation: 'idle',
        randomSeed: 102),
    DecorationConfig(
        id: 'stream_a',
        type: 'grass',
        unlockLevel: 11,
        zone: 'KnowledgeZone',
        density: 0.25,
        asset: 'decor/stream_a.png',
        animation: 'water',
        randomSeed: 111),
    DecorationConfig(
        id: 'bridge_small',
        type: 'bush',
        unlockLevel: 11,
        zone: 'KnowledgeZone',
        density: 0.2,
        asset: 'decor/bridge_small.png',
        animation: 'idle',
        randomSeed: 112),
    DecorationConfig(
        id: 'roadside_tree',
        type: 'tree',
        unlockLevel: 12,
        zone: 'KnowledgeZone',
        density: 0.35,
        asset: 'decor/roadside_tree.png',
        animation: 'sway',
        randomSeed: 121),
    DecorationConfig(
        id: 'flower_line',
        type: 'flower',
        unlockLevel: 12,
        zone: 'KnowledgeZone',
        density: 0.45,
        asset: 'decor/flower_line.png',
        animation: 'idle',
        randomSeed: 122),
    DecorationConfig(
        id: 'stone_step_ring',
        type: 'bush',
        unlockLevel: 13,
        zone: 'CenterZone',
        density: 0.35,
        asset: 'decor/stone_step_ring.png',
        animation: 'idle',
        randomSeed: 131),
    DecorationConfig(
        id: 'book_flowerbed',
        type: 'flower',
        unlockLevel: 14,
        zone: 'KnowledgeZone',
        density: 0.35,
        asset: 'decor/book_flowerbed.png',
        animation: 'page_float',
        randomSeed: 141),
    DecorationConfig(
        id: 'dense_tree_back',
        type: 'tree',
        unlockLevel: 15,
        zone: 'FutureZone',
        density: 0.45,
        asset: 'decor/dense_tree_back.png',
        animation: 'sway',
        randomSeed: 151),
    DecorationConfig(
        id: 'far_hill',
        type: 'grass',
        unlockLevel: 16,
        zone: 'FutureZone',
        density: 0.25,
        asset: 'decor/far_hill.png',
        animation: 'idle',
        randomSeed: 161),
    DecorationConfig(
        id: 'tall_tree',
        type: 'tree',
        unlockLevel: 16,
        zone: 'FutureZone',
        density: 0.35,
        asset: 'decor/tall_tree.png',
        animation: 'sway',
        randomSeed: 162),
    DecorationConfig(
        id: 'lamp_post',
        type: 'bush',
        unlockLevel: 17,
        zone: 'HarborZone',
        density: 0.25,
        asset: 'decor/lamp_post.png',
        animation: 'glow',
        randomSeed: 171),
    DecorationConfig(
        id: 'long_bench',
        type: 'bush',
        unlockLevel: 17,
        zone: 'HarborZone',
        density: 0.2,
        asset: 'decor/long_bench.png',
        animation: 'idle',
        randomSeed: 172),
    DecorationConfig(
        id: 'low_fence',
        type: 'bush',
        unlockLevel: 17,
        zone: 'HarborZone',
        density: 0.25,
        asset: 'decor/low_fence.png',
        animation: 'idle',
        randomSeed: 173),
    DecorationConfig(
        id: 'garden_path',
        type: 'grass',
        unlockLevel: 18,
        zone: 'MemoryZone',
        density: 0.35,
        asset: 'decor/garden_path.png',
        animation: 'idle',
        randomSeed: 181),
    DecorationConfig(
        id: 'courtyard_flower',
        type: 'flower',
        unlockLevel: 18,
        zone: 'MemoryZone',
        density: 0.4,
        asset: 'decor/courtyard_flower.png',
        animation: 'bloom',
        randomSeed: 182),
    DecorationConfig(
        id: 'large_canopy',
        type: 'tree',
        unlockLevel: 19,
        zone: 'FutureZone',
        density: 0.35,
        asset: 'decor/large_canopy.png',
        animation: 'sway',
        randomSeed: 191),
    DecorationConfig(
        id: 'bird_group',
        type: 'flower',
        unlockLevel: 19,
        zone: 'FutureZone',
        density: 0.2,
        asset: 'decor/bird_group.png',
        animation: 'fly',
        randomSeed: 192),
    DecorationConfig(
        id: 'cloud_far',
        type: 'grass',
        unlockLevel: 19,
        zone: 'FutureZone',
        density: 0.25,
        asset: 'decor/cloud_far.png',
        animation: 'drift',
        randomSeed: 193),
    DecorationConfig(
        id: 'full_ecology_pack',
        type: 'tree',
        unlockLevel: 20,
        zone: 'CenterZone',
        density: 0.65,
        asset: 'decor/full_ecology_pack.png',
        animation: 'sway',
        randomSeed: 201),
  ];

  static const paths = <PathConfig>[
    PathConfig(
        id: 'path_center_seed',
        unlockLevel: 2,
        startNode: 'starter_stone',
        endNode: 'starter_stone',
        pathType: 'footprint',
        width: 4),
    PathConfig(
        id: 'path_center_memory',
        unlockLevel: 3,
        startNode: 'starter_stone',
        endNode: 'record_shed',
        pathType: 'dirt',
        width: 5),
    PathConfig(
        id: 'path_memory_loop',
        unlockLevel: 4,
        startNode: 'record_shed',
        endNode: 'memory_mailbox',
        pathType: 'dirt',
        width: 4),
    PathConfig(
        id: 'path_house_core',
        unlockLevel: 5,
        startNode: 'starter_stone',
        endNode: 'growth_house',
        pathType: 'stone',
        width: 6),
    PathConfig(
        id: 'path_house_harbor',
        unlockLevel: 6,
        startNode: 'growth_house',
        endNode: 'harbor_pier',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_emotion_branch',
        unlockLevel: 7,
        startNode: 'growth_house',
        endNode: 'emotion_windchime',
        pathType: 'dirt',
        width: 4),
    PathConfig(
        id: 'path_flowerbed',
        unlockLevel: 8,
        startNode: 'emotion_windchime',
        endNode: 'habit_flowerbed',
        pathType: 'flower',
        width: 4),
    PathConfig(
        id: 'path_tent',
        unlockLevel: 9,
        startNode: 'habit_flowerbed',
        endNode: 'quiet_tent',
        pathType: 'dirt',
        width: 4),
    PathConfig(
        id: 'path_ring_1',
        unlockLevel: 10,
        startNode: 'harbor_pier',
        endNode: 'quiet_tent',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_center_knowledge',
        unlockLevel: 11,
        startNode: 'growth_house',
        endNode: 'lighthouse_base',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_plaza_axis',
        unlockLevel: 12,
        startNode: 'lighthouse_base',
        endNode: 'story_plaza',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_fountain_ring',
        unlockLevel: 13,
        startNode: 'growth_house_lv2',
        endNode: 'memory_fountain',
        pathType: 'stone',
        width: 6),
    PathConfig(
        id: 'path_plaza_library',
        unlockLevel: 14,
        startNode: 'story_plaza',
        endNode: 'library_seed',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_axis_2',
        unlockLevel: 15,
        startNode: 'memory_fountain',
        endNode: 'growth_clocktower',
        pathType: 'stone',
        width: 6),
    PathConfig(
        id: 'path_future_hill',
        unlockLevel: 16,
        startNode: 'growth_clocktower',
        endNode: 'lighthouse',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_social_loop',
        unlockLevel: 17,
        startNode: 'companion_plaza',
        endNode: 'harbor_pier',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_gallery',
        unlockLevel: 18,
        startNode: 'record_shed',
        endNode: 'memory_gallery',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_observatory',
        unlockLevel: 19,
        startNode: 'lighthouse',
        endNode: 'dream_observatory',
        pathType: 'stone',
        width: 5),
    PathConfig(
        id: 'path_world_complete',
        unlockLevel: 20,
        startNode: 'growth_academy',
        endNode: 'dream_observatory',
        pathType: 'gold',
        width: 6),
  ];

  static const anchors = <AnchorConfig>[
    AnchorConfig(
      id: 'anchor_starter',
      anchorBuildingId: 'starter_stone',
      visualWeight: 0.45,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_house',
      anchorBuildingId: 'growth_house',
      visualWeight: 0.70,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_house_upgraded',
      anchorBuildingId: 'growth_house_lv2',
      visualWeight: 0.78,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_fountain',
      anchorBuildingId: 'memory_fountain',
      visualWeight: 0.82,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_clocktower',
      anchorBuildingId: 'growth_clocktower',
      visualWeight: 0.88,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_lighthouse',
      anchorBuildingId: 'lighthouse',
      visualWeight: 0.90,
      cameraFocus: true,
    ),
    AnchorConfig(
      id: 'anchor_academy',
      anchorBuildingId: 'growth_academy',
      visualWeight: 1.0,
      cameraFocus: true,
    ),
  ];

  static const levels = <IslandLevelConfig>[
    IslandLevelConfig(
        level: 1,
        islandRadius: 0.62,
        unlockZones: ['CenterZone'],
        unlockBuildings: ['starter_stone'],
        unlockDecorations: ['grass_patch', 'tiny_flower'],
        unlockPaths: [],
        unlockEffects: ['soft_breeze'],
        unlockWeather: 'clear',
        requiredGrowthScore: 0),
    IslandLevelConfig(
        level: 2,
        islandRadius: 0.64,
        unlockZones: [],
        unlockBuildings: [],
        unlockDecorations: ['footprint_grass'],
        unlockPaths: ['path_center_seed'],
        unlockEffects: [],
        unlockWeather: 'clear',
        requiredGrowthScore: 25),
    IslandLevelConfig(
        level: 3,
        islandRadius: 0.66,
        unlockZones: ['MemoryZone'],
        unlockBuildings: ['record_shed'],
        unlockDecorations: ['guardian_tree'],
        unlockPaths: ['path_center_memory'],
        unlockEffects: ['leaf_float'],
        unlockWeather: 'clear',
        requiredGrowthScore: 55),
    IslandLevelConfig(
        level: 4,
        islandRadius: 0.68,
        unlockZones: [],
        unlockBuildings: ['memory_mailbox'],
        unlockDecorations: ['small_stone', 'bush_low'],
        unlockPaths: ['path_memory_loop'],
        unlockEffects: [],
        unlockWeather: 'clear',
        requiredGrowthScore: 95),
    IslandLevelConfig(
        level: 5,
        islandRadius: 0.70,
        unlockZones: [],
        unlockBuildings: ['growth_house'],
        unlockDecorations: ['center_lawn_ring'],
        unlockPaths: ['path_house_core'],
        unlockEffects: ['house_warm_light'],
        unlockWeather: 'clear',
        requiredGrowthScore: 145),
    IslandLevelConfig(
        level: 6,
        islandRadius: 0.73,
        unlockZones: ['HarborZone'],
        unlockBuildings: ['harbor_pier'],
        unlockDecorations: ['reed_edge', 'shore_rock'],
        unlockPaths: ['path_house_harbor'],
        unlockEffects: ['water_ripple'],
        unlockWeather: 'clear',
        requiredGrowthScore: 205),
    IslandLevelConfig(
        level: 7,
        islandRadius: 0.76,
        unlockZones: ['EmotionZone'],
        unlockBuildings: ['emotion_windchime'],
        unlockDecorations: ['tree_cluster_west'],
        unlockPaths: ['path_emotion_branch'],
        unlockEffects: ['wind_chime_glow'],
        unlockWeather: 'breeze',
        requiredGrowthScore: 275),
    IslandLevelConfig(
        level: 8,
        islandRadius: 0.79,
        unlockZones: [],
        unlockBuildings: ['habit_flowerbed'],
        unlockDecorations: ['flower_group_a'],
        unlockPaths: ['path_flowerbed'],
        unlockEffects: ['petal_idle'],
        unlockWeather: 'breeze',
        requiredGrowthScore: 355),
    IslandLevelConfig(
        level: 9,
        islandRadius: 0.82,
        unlockZones: [],
        unlockBuildings: ['quiet_tent'],
        unlockDecorations: ['soft_cloud_shadow', 'firefly_dot'],
        unlockPaths: ['path_tent'],
        unlockEffects: ['firefly_idle'],
        unlockWeather: 'cloudy',
        requiredGrowthScore: 445),
    IslandLevelConfig(
        level: 10,
        islandRadius: 0.85,
        unlockZones: [],
        unlockBuildings: ['growth_house_lv2'],
        unlockDecorations: ['life_area_fence', 'bench_small'],
        unlockPaths: ['path_ring_1'],
        unlockEffects: ['center_pulse'],
        unlockWeather: 'clear',
        requiredGrowthScore: 545),
    IslandLevelConfig(
        level: 11,
        islandRadius: 0.88,
        unlockZones: ['KnowledgeZone'],
        unlockBuildings: ['lighthouse_base'],
        unlockDecorations: ['stream_a', 'bridge_small'],
        unlockPaths: ['path_center_knowledge'],
        unlockEffects: ['stream_shine'],
        unlockWeather: 'clear',
        requiredGrowthScore: 660),
    IslandLevelConfig(
        level: 12,
        islandRadius: 0.91,
        unlockZones: [],
        unlockBuildings: ['story_plaza'],
        unlockDecorations: ['roadside_tree', 'flower_line'],
        unlockPaths: ['path_plaza_axis'],
        unlockEffects: ['plaza_spark'],
        unlockWeather: 'clear',
        requiredGrowthScore: 790),
    IslandLevelConfig(
        level: 13,
        islandRadius: 0.94,
        unlockZones: [],
        unlockBuildings: ['memory_fountain'],
        unlockDecorations: ['stone_step_ring'],
        unlockPaths: ['path_fountain_ring'],
        unlockEffects: ['fountain_mist'],
        unlockWeather: 'clear',
        requiredGrowthScore: 935),
    IslandLevelConfig(
        level: 14,
        islandRadius: 0.97,
        unlockZones: [],
        unlockBuildings: ['library_seed'],
        unlockDecorations: ['book_flowerbed'],
        unlockPaths: ['path_plaza_library'],
        unlockEffects: ['page_float'],
        unlockWeather: 'breeze',
        requiredGrowthScore: 1095),
    IslandLevelConfig(
        level: 15,
        islandRadius: 1.00,
        unlockZones: [],
        unlockBuildings: ['growth_clocktower'],
        unlockDecorations: ['dense_tree_back'],
        unlockPaths: ['path_axis_2'],
        unlockEffects: ['clock_light'],
        unlockWeather: 'clear',
        requiredGrowthScore: 1270),
    IslandLevelConfig(
        level: 16,
        islandRadius: 1.04,
        unlockZones: ['FutureZone'],
        unlockBuildings: ['lighthouse'],
        unlockDecorations: ['far_hill', 'tall_tree'],
        unlockPaths: ['path_future_hill'],
        unlockEffects: ['lighthouse_beam'],
        unlockWeather: 'clear',
        requiredGrowthScore: 1460),
    IslandLevelConfig(
        level: 17,
        islandRadius: 1.08,
        unlockZones: [],
        unlockBuildings: ['companion_plaza'],
        unlockDecorations: ['lamp_post', 'long_bench', 'low_fence'],
        unlockPaths: ['path_social_loop'],
        unlockEffects: ['life_idle'],
        unlockWeather: 'breeze',
        requiredGrowthScore: 1665),
    IslandLevelConfig(
        level: 18,
        islandRadius: 1.12,
        unlockZones: [],
        unlockBuildings: ['memory_gallery'],
        unlockDecorations: ['garden_path', 'courtyard_flower'],
        unlockPaths: ['path_gallery'],
        unlockEffects: ['gallery_glow'],
        unlockWeather: 'clear',
        requiredGrowthScore: 1885),
    IslandLevelConfig(
        level: 19,
        islandRadius: 1.16,
        unlockZones: [],
        unlockBuildings: ['dream_observatory'],
        unlockDecorations: ['large_canopy', 'bird_group', 'cloud_far'],
        unlockPaths: ['path_observatory'],
        unlockEffects: ['future_glimmer'],
        unlockWeather: 'clear',
        requiredGrowthScore: 2120),
    IslandLevelConfig(
        level: 20,
        islandRadius: 1.20,
        unlockZones: [],
        unlockBuildings: ['growth_academy'],
        unlockDecorations: ['full_ecology_pack'],
        unlockPaths: ['path_world_complete'],
        unlockEffects: ['world_complete_aura'],
        unlockWeather: 'clear',
        requiredGrowthScore: 2370),
  ];

  static ZoneConfig? zoneById(String id) => _find(zones, id);
  static BuildingConfig? buildingById(String id) => _find(buildings, id);
  static DecorationConfig? decorationById(String id) => _find(decorations, id);
  static PathConfig? pathById(String id) => _find(paths, id);

  static T? _find<T>(List<T> items, String id) {
    for (final item in items) {
      final value = switch (item) {
        ZoneConfig c => c.id,
        BuildingConfig c => c.id,
        DecorationConfig c => c.id,
        PathConfig c => c.id,
        _ => '',
      };
      if (value == id) return item;
    }
    return null;
  }
}

class GrowthIslandConfigRepository {
  const GrowthIslandConfigRepository();

  IslandLevelConfig resolveLevel(int level) {
    final active = GrowthIslandConfigs.levels
        .where((config) => config.level <= level)
        .toList(growable: false);
    final current =
        active.isEmpty ? GrowthIslandConfigs.levels.first : active.last;
    return IslandLevelConfig(
      level: current.level,
      islandRadius: current.islandRadius,
      unlockZones: _merge(active.expand((config) => config.unlockZones)),
      unlockBuildings:
          _merge(active.expand((config) => config.unlockBuildings)),
      unlockDecorations:
          _merge(active.expand((config) => config.unlockDecorations)),
      unlockPaths: _merge(active.expand((config) => config.unlockPaths)),
      unlockEffects: _merge(active.expand((config) => config.unlockEffects)),
      unlockWeather: current.unlockWeather,
      requiredGrowthScore: current.requiredGrowthScore,
    );
  }

  List<ZoneConfig> resolveZones(List<String> ids) =>
      ids.map(GrowthIslandConfigs.zoneById).whereType<ZoneConfig>().toList();

  List<BuildingConfig> resolveBuildings(List<String> ids) => ids
      .map(GrowthIslandConfigs.buildingById)
      .whereType<BuildingConfig>()
      .toList();

  List<DecorationConfig> resolveDecorations(List<String> ids) => ids
      .map(GrowthIslandConfigs.decorationById)
      .whereType<DecorationConfig>()
      .toList();

  List<PathConfig> resolvePaths(List<String> ids) =>
      ids.map(GrowthIslandConfigs.pathById).whereType<PathConfig>().toList();

  List<String> _merge(Iterable<String> values) {
    final seen = <String>{};
    final out = <String>[];
    for (final value in values) {
      if (seen.add(value)) out.add(value);
    }
    return out;
  }
}
